---
# Source: tmplt/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echo-tmplt
  labels:
    app.kubernetes.io/name: tmplt
    app.kubernetes.io/instance: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tmplt
      app.kubernetes.io/instance: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tmplt
        app.kubernetes.io/instance: echo
    spec:
      containers:
        - name: tmplt
          image: "brndnmtthws/nginx-echo-headers:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {}
            
