apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "rundeck.name" . }}
    helm.sh/chart: {{ include "rundeck.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-ansible
data:
  ansible.cfg: {{ toYaml .Values.rundeck.ansibleConfig | indent 2 }}
  hosts: {{ toYaml .Values.rundeck.ansibleInventory | indent 2 }}
