---
# Source: tmplt/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: echo-nodeport
  labels:
    app.kubernetes.io/name: tmplt
    app.kubernetes.io/instance: echo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tmplt
    app.kubernetes.io/instance: echo
